# Generated by Django 4.2.6 on 2023-10-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
